<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateQuestionnairesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('questionnaires', function (Blueprint $table) {
            $table->id();
            $table->integer('que_numero')->default(0);
            $table->string('que_quizz',150);
            $table->integer('que_semaine')->default(0);
            $table->integer('que_annee')->default(0);
            $table->date('que_date');
            $table->string('que_op',50);
            $table->string('que_identifiant',4);
            $table->string('que_nom',100);
            $table->string('que_prenom',150);
            $table->string('que_login',150);
            $table->integer('que_duree')->default(0);
            $table->string('que_poste',50);
            $table->integer('que_nbreques')->default(0);
            $table->string('que_q1theme',100);
            $table->text('que_q1');
            $table->integer('que_nbrerepq1')->default(0);
            $table->integer('que_choixrepq1')->default(0);
            $table->text('que_q1r1');
            $table->text('que_q1r2');
            $table->text('que_q1r3');
            $table->text('que_q1r4');
            $table->integer('que_q1br')->default(0);
            $table->float('que_noteq1');
            $table->string('que_q2theme',100);
            $table->text('que_q2');
            $table->integer('que_nbrerepq2')->default(0);
            $table->integer('que_choixrepq2')->default(0);
            $table->text('que_q2r1');
            $table->text('que_q2r2');
            $table->text('que_q2r3');
            $table->text('que_q2r4');
            $table->integer('que_q2br')->default(0);
            $table->float('que_noteq2');
            $table->string('que_q3theme',100);
            $table->text('que_q3');
            $table->integer('que_nbrerepq3')->default(0);
            $table->integer('que_choixrepq3')->default(0);
            $table->text('que_q3r1');
            $table->text('que_q3r2');
            $table->text('que_q3r3');
            $table->text('que_q3r4');
            $table->integer('que_q3br')->default(0);
            $table->float('que_noteq3');
            $table->string('que_q4theme',100);
            $table->text('que_q4');
            $table->integer('que_nbrerepq4')->default(0);
            $table->integer('que_choixrepq4')->default(0);
            $table->text('que_q4r1');
            $table->text('que_q4r2');
            $table->text('que_q4r3');
            $table->text('que_q4r4');
            $table->integer('que_q4br')->default(0);
            $table->float('que_noteq4');
            $table->string('que_q5theme',100);
            $table->text('que_q5');
            $table->integer('que_nbrerepq5')->default(0);
            $table->integer('que_choixrepq5')->default(0);
            $table->text('que_q5r1');
            $table->text('que_q5r2');
            $table->text('que_q5r3');
            $table->text('que_q5r4');
            $table->integer('que_q5br')->default(0);
            $table->float('que_noteq5');
            $table->string('que_q6theme',100);
            $table->text('que_q6');
            $table->integer('que_nbrerepq6')->default(0);
            $table->integer('que_choixrepq6')->default(0);
            $table->text('que_q6r1');
            $table->text('que_q6r2');
            $table->text('que_q6r3');
            $table->text('que_q6r4');
            $table->integer('que_q6br')->default(0);
            $table->float('que_noteq6');
            $table->string('que_q7theme',100);
            $table->text('que_q7');
            $table->integer('que_nbrerepq7')->default(0);
            $table->integer('que_choixrepq7')->default(0);
            $table->text('que_q7r1');
            $table->text('que_q7r2');
            $table->text('que_q7r3');
            $table->text('que_q7r4');
            $table->integer('que_q7br')->default(0);
            $table->float('que_noteq7');
            $table->string('que_q8theme',100);
            $table->text('que_q8');
            $table->integer('que_nbrerepq8')->default(0);
            $table->integer('que_choixrepq8')->default(0);
            $table->text('que_q8r1');
            $table->text('que_q8r2');
            $table->text('que_q8r3');
            $table->text('que_q8r4');
            $table->integer('que_q8br')->default(0);
            $table->float('que_noteq8');
            $table->string('que_q9theme',100);
            $table->text('que_q9');
            $table->integer('que_nbrerepq9')->default(0);
            $table->integer('que_choixrepq9')->default(0);
            $table->text('que_q9r1');
            $table->text('que_q9r2');
            $table->text('que_q9r3');
            $table->text('que_q9r4');
            $table->integer('que_q9br')->default(0);
            $table->float('que_noteq9');
            $table->string('que_q10theme',100);
            $table->text('que_q10');
            $table->integer('que_nbrerepq10')->default(0);
            $table->integer('que_choixrepq10')->default(0);
            $table->text('que_q10r1');
            $table->text('que_q10r2');
            $table->text('que_q10r3');
            $table->text('que_q10r4');
            $table->integer('que_q10br')->default(0);
            $table->float('que_noteq10');
            $table->string('que_q11theme',100);
            $table->text('que_q11');
            $table->integer('que_nbrerepq11')->default(0);
            $table->integer('que_choixrepq11')->default(0);
            $table->text('que_q11r1');
            $table->text('que_q11r2');
            $table->text('que_q11r3');
            $table->text('que_q11r4');
            $table->integer('que_q11br')->default(0);
            $table->float('que_noteq11');
            $table->string('que_q12theme',100);
            $table->text('que_q12');
            $table->integer('que_nbrerepq12')->default(0);
            $table->integer('que_choixrepq12')->default(0);
            $table->text('que_q12r1');
            $table->text('que_q12r2');
            $table->text('que_q12r3');
            $table->text('que_q12r4');
            $table->integer('que_q12br')->default(0);
            $table->float('que_noteq12');
            $table->string('que_q13theme',100);
            $table->text('que_q13');
            $table->integer('que_nbrerepq13')->default(0);
            $table->integer('que_choixrepq13')->default(0);
            $table->text('que_q13r1');
            $table->text('que_q13r2');
            $table->text('que_q13r3');
            $table->text('que_q13r4');
            $table->integer('que_q13br')->default(0);
            $table->float('que_noteq13');
            $table->string('que_q14theme',100);
            $table->text('que_q14');
            $table->integer('que_nbrerepq14')->default(0);
            $table->integer('que_choixrepq14')->default(0);
            $table->text('que_q14r1');
            $table->text('que_q14r2');
            $table->text('que_q14r3');
            $table->text('que_q14r4');
            $table->integer('que_q14br')->default(0);
            $table->float('que_noteq14');
            $table->string('que_q15theme',100);
            $table->text('que_q15');
            $table->integer('que_nbrerepq15')->default(0);
            $table->integer('que_choixrepq15')->default(0);
            $table->text('que_q15r1');
            $table->text('que_q15r2');
            $table->text('que_q15r3');
            $table->text('que_q15r4');
            $table->integer('que_q15br')->default(0);
            $table->float('que_noteq15');
            $table->string('que_q16theme',100);
            $table->text('que_q16');
            $table->integer('que_nbrerepq16')->default(0);
            $table->integer('que_choixrepq16')->default(0);
            $table->text('que_q16r1');
            $table->text('que_q16r2');
            $table->text('que_q16r3');
            $table->text('que_q16r4');
            $table->integer('que_q16br')->default(0);
            $table->float('que_noteq16');
            $table->string('que_q17theme',100);
            $table->text('que_q17');
            $table->integer('que_nbrerepq17')->default(0);
            $table->integer('que_choixrepq17')->default(0);
            $table->text('que_q17r1');
            $table->text('que_q17r2');
            $table->text('que_q17r3');
            $table->text('que_q17r4');
            $table->integer('que_q17br')->default(0);
            $table->float('que_noteq17');
            $table->string('que_q18theme',100);
            $table->text('que_q18');
            $table->integer('que_nbrerepq18')->default(0);
            $table->integer('que_choixrepq18')->default(0);
            $table->text('que_q18r1');
            $table->text('que_q18r2');
            $table->text('que_q18r3');
            $table->text('que_q18r4');
            $table->integer('que_q18br')->default(0);
            $table->float('que_noteq18');
            $table->string('que_q19theme',100);
            $table->text('que_q19');
            $table->integer('que_nbrerepq19')->default(0);
            $table->integer('que_choixrepq19')->default(0);
            $table->text('que_q19r1');
            $table->text('que_q19r2');
            $table->text('que_q19r3');
            $table->text('que_q19r4');
            $table->integer('que_q19br')->default(0);
            $table->float('que_noteq19');
            $table->string('que_q20theme',100);
            $table->text('que_q20');
            $table->integer('que_nbrerepq20')->default(0);
            $table->integer('que_choixrepq20')->default(0);
            $table->text('que_q20r1');
            $table->text('que_q20r2');
            $table->text('que_q20r3');
            $table->text('que_q20r4');
            $table->integer('que_q20br')->default(0);
            $table->float('que_noteq20');
            $table->string('que_editeok',1);
            $table->integer('que_locked')->default(0);
            $table->integer('que_resize')->default(0);
            $table->integer('que_size')->default(0);              
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('questionnaires');
    }
}
